{ ScriptType
title: Children of Men Scene Rewrite
author: Alfonso Cuaron & Tyler Childs
contact: yo@tychi.me
agent: team@sillyz.computer

# INT. JASPER'S CAR - DRIVING CONTINUOUS

@ THEO
" How's Janice?

@ JASPER
" She's lovely.

@ JASPER
(sighs
" Tends to wander off occasionally.

@ JASPER
" I tound her last week on the other side of the brook. Mud all over her nightgown, shivering a death of cold, poor thing.

@ THEO
" I'm sorry.

@ JASPER
" She feels worthless. She feels a burden to me. When she's lucid, she remembers what we used to be.

# EXT. WOODEDROAD DUSK
The Volvo slows down, and makes a left turn, going off the road, stopping in front the woods.

Jasper and Theo get out. Jasper walks to the middle of the empty road, looking both ways.

@ JASPER
" A couple weeks ago, I came on this Dutch bloke, lost out back in the woods. Poor soul, wasn't much left of him. Remember the pictures of those starving wretches in Ethiopia? same thing, only blond. He said he'd escaped from Bexhill. They dug a tunnel under the fence and came over, 200 of them. Mostly French, Spaniards...
(emphasis for Theo
" ... a few Americans. They were crossing no man's land. Soldiers caught them. Lined them up, shot them down. 200 hundred refugees. unarmed. Barn. Just like that. Keeping England Alive. It didn't make the news.

@ THEO
" Not surprising.

Assured the coast is clear, Jasper walks toward a row of bushes in front of the trees, illuminated by the headlights.

@ JASPER
" somehow this bloke escaped, got through no man's land, got over that hill. I gave him some food. Amigo, he told me some spooky stories about what's happening in Europe. Atrocities you'd never believe. And the look in his eyes.

Theo walking with Jasper toward the bushes.

@ JASPER
" It's sick. What humans can do to each other.

Jasper removes one of the bushes -- it's not rooted.

@ JASPER
" I offered to hide him. He refused. Said he had to get to London. Said he had friends there. He left. All the way to London, no papers.

@ THEO
" He won't make it.

@ JASPER
" I know.

Theo removes another bush. This is a false hedge, hiding a tiny dirt path behind it.

@ JASPER
" But I'd like to think he would.

# EXT. DIRT PATH DUSK
Through the woods, Jasper's car crossing the dirt path, the headlights on.

Through the windshield, in a clearing in the trees, visible in the last light of day: a low-tech, jury-rigged eco-house, complete with primitive solar panels and a grass roof.

Jasper navigates the dirt path carefully.

# INT. JASPER'S HOUSE NIGHT

The Stones' "Ruby Tuesday" plays. JANICE (70) sits in a chair, staring ahead. She was young in the 60's, and now is old. The light is gone from her eyes, her face a blank mask.

@ JASPER
" Hi, Sweetie.

Jasper kisses her. Janice does not react.

@ JASPER
" Theo's here. He came for a little visit. Theo, remember? Your Rebel With a Lost Cause?

Jasper motions Theo over.

@ THEO
" Hi, Janice.

No response from Janice. She is staring at a wall of photos.

Her lifetime frozen in images. A shrine to her past.

@ JASPER
" She's not always like this. She's in and out.

# INT. JASPER'S KITCHEN NIGHT
Jasper and Theo at the kitchen table, eating vegetable soup.

Jasper eats a spoonful of soup, looking at Theo.

@ JASPER
( starting a joke
" So there's this supper. Scientists and wise men, you know, Human Project, that sort of bullocks.

@ THEO
(rolling with it
" Yeah

@ JASPER
" They're throwing around theories about the ultimate question: how is it that human beings haven't had babies in 18 years?

Theo ponders a potato.

@ JASPER
" The biologist blames genetic experiments that altered DNA. The environmentalist says that pollution and bio-experiments poisoned the water. You know, the typical jada jada.

Theo nods.

@ JASPER
" A New Age bloke claims Mama Nature is merely protecting herself. Then they all look at this English scientist, who hasn't said a word, he just keeps eating.

They both eat a spoonful of soup.

@ JASPER
" They ask him, "So, what do you think? Why don't people have babies anymore?" The English bloke looks at them, he's chewing on a wing
(thick English accent
" "I haven't a clue," he says. "But this stork is quite lovely, isn't it?"

Jasper playfully hits Theo.

@ JASPER
" waaahl You get it -- he's eating a stork!

@ THEO
(smiles
" Stork. That's funny.
