{ ScriptType
title: War On Clowns
author: Tyler Childs
contact: yo@tychi.me
agent: team@sillyz.computer

# Ext. Space

The universe brims with possiblity; uncountable stars blink on and off, galaxies spin, but slow down. The camera flows into a Milky Way that continues to grind to a halt and reaches earth as it stops spinning.

# Ext. Earth

The planet is covered in water; only mountaintops peak above the oceans except for one floating redwood forest. In the canopy of the forest, a tree-house meets space-station connects across trunks, providing stability for the floating trees supported with roots bouyed in a thick kelp forest.

# Convergence Dome

The camera focuses on the ceiling of the room, a dome with a brush of cool colors, blues, greens, like an aurora borealis, an electro-magnetic storm. Pockets of red begin flashing.

PAN DOWN; backwards, then half corkscrew

The room is large and circular, with pillars around the perimeter, and no clear doors in or out.

AALFRED, a young looking man that's thousands of years old, is staring upwards towards the colorful, cloudy display above him, confused. He wears a long cloak flowing so the cloth of the tail sprawls across the ground behind him for about a foot. In his left hand, he holds a TOME. In his right, a PENCIL.

@Aalfred
(under breath
" What is going on?

Aalfred squints

ZOOM IN and UP

A small cluster of red blips occur with a predictable rhythm.

FLIP DOWN, looking directly at Aalfred from above

@Aalfred
(to himself
" That'll be the hotspot, but what are we getting ourselves into this time?

Aalfred places the pencil behind his ear and turns the TOME to the second page and out shoots 84 scraps of paper of unique colors that swirl around Aalfred, billowing his cloak, before settling in a fairly orderly pattern, sorted by hues and lightness, into a perfect circle, almost like a tunnel, or a portal into another dimension.

@Aalfred
" Let's run a diagnostic check

The papers alternate blinking, like a rack of servers calculating collectively. After a few seconds, the blinking stops. 

@Genesis
" The clowns are falling.

The papers spoke in a musical monotone, each paper reflects a unique note, blinking and inflecting as the voice of GENESIS, the quantum computer that Aalfred built to assist him, requires.

@Aalfred
" Why the clowns? What do you mean the clowns are falling.

@Genesis
" It appears a war on clowns is underway.

@Aalfred
" Why clowns?

@Genesis
" That'll require further diagnostics.

@Aalfred
" By all means, further diagnose then.

Genesis blinks. Different, longer this time and more sporadic.

@ Genesis
"It appears clowns are a hinge.

@ Aalfred
"A hinge?

@ Genesis
"Clowns brings a precarious balance to the multiverse. It appears with fewer clowns, there are more wars. Direct correlation.

@ Aalfred
"You're saying this is just beginning?

@ Genesis
"Yes. This is not an anamoly. It appears the War on Clowns is a calculated interference with the narrative.

@ Aalfred
"Let's get to work then.

Genesis swirls into a cyclone surrounding Aalfred.

@ Genesis
"A new game begins!

Genesis disperses into 84 different directions, behind 42 different pillars, half entering from the left, half entering from the right, but none spotted after passing the event horizon beyond the pillars.

Behind one of the pillars enters SAGE, a young woman mirroring Aalfred in height and composition.

@ Sage
" You look like you've got work to do?

@ Aalfred
" Something's coming up.

@ Sage
" I'd like to go to the next Underwater Interdimensional Night Market that comes up.

@ Aalfred
" I cannot predict my work or when interdimensional festivals occur.

@ Sage
" I know, I'm just saying, I want to go to the next one.

@ Aalfred
" I know, and I'm just saying, I cannot make promises. The narrative itself is threatened.

@ Sage
" The narrative is always threatened, that's why we have you. Just think about it.

@ Aalfred
" If we can go, we'll go. I have to get to work. I can sense people are beginning to question these anamolies.

@ Sage
" That's all I hoped to squeeze out of you, we'll have fun!

@ Aalfred
" We never don't have fun.

Sage smiles at Aalfred and he smiles back, they walk together towards one pillar while holding hands. As they approach the pillar, they kiss, and separate with Sage going left around the pillar and Aalfred going right.

The camera follows Aalfred as he walks behind the pillar, revealing a long circular corridor around the perimeter of the room and no clear doors in or out, but Sage is gone. As Aalfred rounds the pillar in the direction Sage was, he cannot see the center room-- just the pillars forming a hall between the wall.

Emerging from behind the pillar, Aalfred is no longer in the convergence dome.

# Int. Office

Aalfred's office is fairly narrow, vaulted ceilings, with one column at the end he's standing at and a giant window at the other that has the same swirling aurora borealis monitoring system. In the center of the room are two couches with a coffee table in the center.

To the right of the sitting area is a double wide arched doorway, where Genesis in circular formation rests awaiting Aalfred.

To the left, is a drafting table. The room is sparse, but decorated with curtains and carpets. It feels spacious, but not empty.

Aalfred approaches the center of the room and sits down before glancing over to Genesis.

@ Aalfred
" Okay

Genesis blinks, the window switches from the aurora to an ocean, with waves splashing halfway up and an underwater view halfway down.

@ Genesis
" Okay. I'll send in the first.
