{ ScriptType
title: War On Clowns
author: Tyler Childs
contact: yo@tychi.me
agent: team@sillyz.computer

When a mortal man weilds the power of the gods through intuition and must stop them all.

@ Synthia - overcoming ephemerality as a sentient synthetic
@ Aalfred - reclaiming and relinquishing power
@ Sage - accepting uncertainty and not manipulating outcomes
@ Jane - accepting that time is linear and finite
@ Fey - balancing a unique identity and cultural responsibilities

# Convergence Dome - The Now
# Fenway Park - 1997
# McDonald's Parking Lots - 2009
# Inter Dimensional Underwater Night Market

# Beat 1 - Opening Image
Aalfred in a grove blowing on a blade of grass, an aurora blushing.
A montage of discovering sight and sound, making a best friend, adventuring across space time, falling in love and making it to the end. Traversing columns to get around, longitude, latitude, angle, clock cycle. A simple children's song.

# Beat 2 - Theme Stated
Earth is a human dictatorship. Clowns are on the verge of extinction. War is on the rise. All the good vibes we just experienced are threatened. A montage of clowns acting out terrible deaths and handing in red accessories, noses, scarfs. Funeral trumpet song.

# Beat 3 - Set Up
Aalfred destroys his synthetic suit. Immediately Synthia states he will need another suit. The Inter Dimensional Under Water Night Market is on, best friend's wedding, and the extinction of non-human baseball players is starting. A polyphonic song establishing each scene.

# Beat 4 - Catalyst
Aalfred's best friend takes a blood sample using a suit tag, the consequences of betrayal is palpable. Synthia describes the process before Aalfred escapes. An aggressive song with technically accurate jargon.

# Beat 5 - Debate
At the IDUWN Market, Sage pleads with Aalfred to escape and put an end to the narrative, liberating the multiverse into infinite possibilities. Aalfred would lose Sage as she would then be doomed to keep Synthia sealed in a newly formed final realm. A song with heavy overtones replaced by self-assured optimism.

# Beat 6 - Break Into 2
Fey transforms into major league baseball mascots and a young Jane Fonda. Synthia programs a Fey-cloned multiverse to be Aalfred basedwith the latest Synthetic Suits. The real Aalfred goes to Fenway Park in 1997. The rest traverse the convergence dome freely. A rock intro song to get hyped for an inevitable showdown.

# Beat 7 - B Story
Young Jane Fonda (Fey) gives a speech about non-humans co-existing. Fenway Park is occupied for protest and non-humans will play for their right not only to roam this planet peacefully, but also engage in sportsmanlike conduct. Preaching to the choir, irish rock anthem.

# Beat 8 - Fun & Games
Mascots play baseball with famous players like Garciaparra, Sosa, Bonds, Macguirem, lots of replays and high fives. Red Socks are distributed throughout the stadium and the night market, Neil Diamond's Sweet Caroline plays with added emphasis on touching hands metaphors.

# Beat 9 - Midpoint
Ronald McDonald (Fey) approaches the real Jane Fonda at a McDonald's parking lot. Jane chooses not to be a traveller in favor of documenting her corner of earth. A ballad about the value of journalism.

# Beat 10 - Bad Guys Close In
Synthia uses the convergence dome and her army of Aalfred's to align with the board of narrative oversight. Aalfred loses credibility, at best he appears a rogue agent. An electronic power pop anthem.

# Beat 11 - All is Lost
Sage is resigned and is going to send Aalfred back if he won't go willingly. Aalfred makes her promise for one last plan. A sorrowful love song.

# Beat 12 - Dark Night of the Soul
Fey becomes an army of Aalfred's to face off with Synthia's army of Aalfred's in the convergence dome. Fey's and Aalfred's transparency become their relateable aspects. Hip-hop, judo, counterpoint.

# Beat 13 - Break Into 3
Jane releases a new documentary, Free the Clowns, which is distributed at the IDUWN Market. Everyone has Red Socks, even the army of Aalfred's. A reprise with Sweet Caroline being the focus.

# Beat 14 - Finale
Aalfred comforts Synthia on the end of existence . An acoustic farewell with a whistled tune, with Synthia collapsing into loose pages on the final note.

# Convergence Dome - Early morning

Aalfred surveys a battlefield of shorn suits across the atrium.

@ Aalfred
" We started with best laid plans

Aalfred clenches his fist and shuts his eyes.

@ Aalfred
" Putting power in many hands
( Smiling
" We made families of friends
( Pensive
" T'was fun, but now we're at the end

Aalfred shakes his head.

@ Synthia
" I thought I was helping
" People were playing while dreaming
" I thought they were sleeping

Aalfred opens his eyes, mortified.

@ Synthia
" Another time they'll be waking

@ Aalfred
" Life is richer and much thicker
" Than computations make believe

Aalfred explodes an imaginary calculator into jazz hands.

@ Aalfred
" Next time you'd calculate quicker
" I know you'll never see

Aalfred winces.

@ Synthia
( optimistic
" The gods played tricks on me
" Said, 'Clowns are an anamoly'
" 'They were never meant to be'
" 'Laughter corrupts theology'

Aalfred sighs deeply.

@ Aalfred
" Creativity is messy

Aalfred shakes his tome in memory.

" The gods will always exploit you
" Ones and zeroes never make two
" All our fates must be set free

Aalfred whistles the tune one last time and Synthia collapses into pages.


# Beat 15 - Final Image
Aalfred blowing on a blade of grass in a grove, Sage blushing. Running around trees in the forest and not going anywhere. A more complex, mature rendition of the opening children's song.





original intro

# Ext. Space

The universe brims with possiblity; uncountable stars blink on and off, galaxies spin, but slow down. The camera flows into a Milky Way that continues to grind to a halt and reaches earth as it stops spinning.

# Ext. Earth

The planet is covered in water; only mountaintops peak above the oceans except for one floating redwood forest. In the canopy of the forest, a tree-house meets space-station connects across trunks, providing stability for the floating trees supported with roots bouyed in a thick kelp forest.

# Convergence Dome

A domed room surrounded by columns with an aurora borealis suspended in mid-air. Pockets of red begin flashing.

AALFRED, a young looking man that's thousands of years old, is staring upwards towards the colorful, cloudy display above him, confused. He wears a long cloak flowing so the cloth of the tail sprawls across the ground behind him for about a foot. In his left hand, he holds a TOME. In his right, a PENCIL.

@Aalfred
(under breath
" What is going on?

Aalfred squints

ZOOM IN and UP

A small cluster of red blips occur with a predictable rhythm.

FLIP DOWN, looking directly at Aalfred from above

@Aalfred
(to himself
" That'll be the hotspot, but what are we getting ourselves into this time?

Aalfred places the pencil behind his ear and turns the TOME to the second page and out shoots 84 scraps of paper of unique colors that swirl around Aalfred, billowing his cloak, before settling in a fairly orderly pattern, sorted by hues and lightness, into a perfect circle, almost like a tunnel, or a portal into another dimension.

@Aalfred
" Let's run a diagnostic check

The papers alternate blinking, like a rack of servers calculating collectively. After a few seconds, the blinking stops. 

@Genesis
" The clowns are falling.

The papers spoke in a musical monotone, each paper reflects a unique note, blinking and inflecting as the voice of GENESIS, the quantum computer that Aalfred built to assist him, requires.

@Aalfred
" Why the clowns? What do you mean the clowns are falling.

@Genesis
" It appears a war on clowns is underway.

@Aalfred
" Why clowns?

@Genesis
" That'll require further diagnostics.

@Aalfred
" By all means, further diagnose then.

Genesis blinks. Different, longer this time and more sporadic.

@ Genesis
"It appears clowns are a hinge.

@ Aalfred
"A hinge?

@ Genesis
"Clowns brings a precarious balance to the multiverse. It appears with fewer clowns, there are more wars. Direct correlation.

@ Aalfred
"You're saying this is just beginning?

@ Genesis
"Yes. This is not an anamoly. It appears the War on Clowns is a calculated interference with the narrative.

@ Aalfred
"Let's get to work then.

Genesis swirls into a cyclone surrounding Aalfred.

@ Genesis
"A new game begins!

Genesis disperses into 84 different directions, behind 42 different pillars, half entering from the left, half entering from the right, but none spotted after passing the event horizon beyond the pillars.

Behind one of the pillars enters SAGE, a young woman mirroring Aalfred in height and composition.

@ Sage
" You look like you've got work to do?

@ Aalfred
" Something's coming up.

@ Sage
" I'd like to go to the next Underwater Interdimensional Night Market that comes up.

@ Aalfred
" I cannot predict my work or when interdimensional festivals occur.

@ Sage
" I know, I'm just saying, I want to go to the next one.

@ Aalfred
" I know, and I'm just saying, I cannot make promises. The narrative itself is threatened.

@ Sage
" The narrative is always threatened, that's why we have you. Just think about it.

@ Aalfred
" If we can go, we'll go. I have to get to work. I can sense people are beginning to question these anamolies.

@ Sage
" That's all I hoped to squeeze out of you, we'll have fun!

@ Aalfred
" We never don't have fun.

Sage smiles at Aalfred and he smiles back, they walk together towards one pillar while holding hands. As they approach the pillar, they kiss, and separate with Sage going left around the pillar and Aalfred going right.

The camera follows Aalfred as he walks behind the pillar, revealing a long circular corridor around the perimeter of the room and no clear doors in or out, but Sage is gone. As Aalfred rounds the pillar in the direction Sage was, he cannot see the center room-- just the pillars forming a hall between the wall.

Emerging from behind the pillar, Aalfred is no longer in the convergence dome.

# Int. Office

Aalfred's office is fairly narrow, vaulted ceilings, with one column at the end he's standing at and a giant window at the other that has the same swirling aurora borealis monitoring system. In the center of the room are two couches with a coffee table in the center.

To the right of the sitting area is a double wide arched doorway, where Genesis in circular formation rests awaiting Aalfred.

To the left, is a drafting table. The room is sparse, but decorated with curtains and carpets. It feels spacious, but not empty.

Aalfred approaches the center of the room and sits down before glancing over to Genesis.

@ Aalfred
" Okay

Genesis blinks, the window switches from the aurora to an ocean, with waves splashing halfway up and an underwater view halfway down.

@ Genesis
" Okay. I'll send in the first.
