{ ScriptType
title: War On Clowns
author: Tyler Childs
contact: yo@tychi.me
agent: team@sillyz.computer

When a mortal man weilds the power of the gods through intuition and must stop them all.

@ Synthia - overcoming ephemerality as a sentient synthetic
@ Aalfred - reclaiming and relinquishing power
@ Sage - accepting uncertainty and not manipulating outcomes
@ Jane - accepting that time is linear and finite
@ Fey - balancing a unique identity and cultural responsibilities

# Convergence Dome - The Now
# Fenway Park - 1997
# McDonald's Parking Lots - 2009
# Inter Dimensional Under Water Night Market

# Beat 1 - Opening Image - D Major
Aalfred in a grove blowing on a blade of grass, an aurora blushing.
A montage of discovering sight and sound, making a best friend, adventuring across space time, falling in love and making it to the end. Traversing columns to get around, longitude, latitude, angle, clock cycle. A simple children's song.

# A Redwood Forest

At the base, AALFRED, a young boy serenades the tree.

@ Aalfred
"o-o-o-o oooo
"o-o-o-o oooo

In the distant wood, a fog glows with a pulse of orange, to the beat.

@ Sage (V.O.)
" Middle D. 62.

Aalfred plucks a blade of grass, blowing on it between his thumbs.

@ Aalfred
"ee-ee e-e-e-e
"ee-ee e-e-e-e

The trees reverberate with this groove, more warm colors glow in a spreading fog.

@ Sage (V.O.)
( Echoing
" Perfect pitch.

Up close, the grass stays suspended in mid-air as Aalfred peels away his thumbs and mouth.

@ Aalfred
(whistling a 12-bar tune

The birds continue with it, as the clouds sparkle blue and purple.

@ Sage (V.O.)
" Natural harmony.

Aalfred jumps up, then stomps and claps a beat.

@Aalfred
(stomp, clap stomp, clap
(stomp, clap, stomp, clap

And the rocks and sticks, flip and slap on loop and in time.

@ Sage (V.O.)
Reverberating resonance rhythm.

Aalfred and the serenaded tree are encompassed by musical mist.

@ Aalfred
" Whoa

Aalfred walks towards the tree as it rolls down before him, and the earth up behind him.

# Beat 2 - Theme Stated - C Minor
Earth is a human dictatorship. Clowns are on the verge of extinction. War is on the rise. All the good vibes we just experienced are threatened. A montage of clowns acting out terrible deaths and handing in red accessories, noses, scarfs. Funeral trumpet song.

# Convergence dome - Int. Day
A domed room with perimetrical columns and an aurora borealical musical mist all up in the area.

Pockets of red flash.

@ Sage (V.O.)
" Middle C. 60.

AALFRED, tens of thousands of years old, but still fly as hell in a jet black suit, no tie, looks up.

@Aalfred
(under breath
" What is going on?

A beat of red pulses is predictable, Aalfred beats his PENCIL to his TOME.

@ Aalfred
(tap tap tap-tap-tap
(tap tap tap-tap-tap

Aalfred places the pencil behind his ear and turns the tome to the second page.

@ Aalfred
" Come on out
( Whistles a high D

From behind the columns, SYNTHIA, is formed from 84 unique leaves in a rainbow spiral tunnel.

@ Synthia
" On your beat.

@Aalfred
" Let's run a diagnostic check.

The leaves rustle and glow in a low pitched rhythm. The leaves speak in a melodic tune. 

@ Synthia
" The clowns are falling.

Aalfred closes his tome and gives Synthia his undivided attention.

@ Aalfred
" Why the clowns? What do you mean the clowns are falling.

@ Synthia
" It appears a war on clowns is underway.

Synthia forms herself into a pixelated clown face.

The red nose pops and Synthia falls to the ground.

@ Aalfred
" Why clowns?

Synthia pulsates her answer as a pile on the ground.

@ Synthia
" That'll require further diagnostics.

Synthia reforms into a rainbow spiral.

@ Aalfred
" By all means, further diagnose then.

A more sporadic, but low pitched rhythm hums as Synthia's leaves pulse.

@ Synthia
" It appears clowns are a hinge.

Aalfred rotates his pencil 90 degrees in front of his face.

@ Aalfred
" A hinge?

@ Synthia
" The Serenaded Tree was your hinge. Clowns bring a precarious balance to the multiverse.

Synthia grows into a pixelated tree that folds back to reveals her spiral form as the canopy.

@ Aalfred
" I walked here. You can't walk up a clown.

@ Synthia
" The reach of just one clown is great. Beyond their own life, before their beginning.

Synthia forms into a mobius strip and animates in a colorful loop.

@ Aalfred
" I've met many a clown. I know how powerful all clowns are.

@ Synthia
" Time check. This is not an anamoly and therefore, requires attention.

Synthia scatters, each leaf shooting like a star around the various columns before disappearing.

@ Aalfred
" Let's get to work then.

Behind one of the pillars enters SAGE, wearing Aalfred's suit, but white, and with a tie.

@ Sage
" You look like you've got work to do?

@ Aalfred
" Something's coming up.

@ Sage
" I'd like to go to the next Inter Dimensional Under Water Night Market that comes up.

@ Aalfred
" I cannot predict my work or when the interdimensional festival occurs.

Sage smiles at Aalfred and he smiles back.

@ Sage
" I know, I'm just saying, I want to go to the next one.

@ Aalfred
" I know, and I'm just saying, I cannot make promises. The narrative itself is threatened.

They walk together towards one pillar while holding hands.

@ Sage
" The narrative is always threatened, that's why we have you. Just think about it.

@ Aalfred
" If we can go, we'll go. I have to get to work. I can sense people are beginning to question these anamolies.

As they approach the pillar, they kiss.

@ Sage
" That's all I hoped to squeeze out of you, we'll have fun!

Sage going left around the pillar.

@ Aalfred
" We never don't have fun.

Aalfred goes right.

# Beat 3 - Set Up
Aalfred destroys his synthetic suit. Immediately Synthia states he will need another suit. The Inter Dimensional Under Water Night Market is on, best friend's wedding, and the extinction of non-human baseball players is starting. A polyphonic song establishing each scene.

# Beat 4 - Catalyst
Aalfred's best friend takes a blood sample using a suit tag, the consequences of betrayal is palpable. Synthia describes the process before Aalfred escapes. An aggressive song with technically accurate jargon.

# Beat 5 - Debate
At the IDUWN Market, Sage pleads with Aalfred to escape and put an end to the narrative, liberating the multiverse into infinite possibilities. Aalfred would lose Sage as she would then be doomed to keep Synthia sealed in a newly formed final realm. A song with heavy overtones replaced by self-assured optimism.

# Beat 6 - Break Into 2
Fey recruits major league baseball mascots, 1997 Jane Fonda, and Neil Diamond. Synthia programs a Fey-cloned multiverse to be Aalfred basedwith the latest Synthetic Suits. The real Aalfred goes to Fenway Park in 1997. The rest traverse the convergence dome freely. A rock intro song to get hyped for an inevitable showdown.

# Beat 7 - B Story
Young Jane Fonda (Fey) gives a speech about non-humans co-existing. Fenway Park is occupied for protest and non-humans will play for their right not only to roam this planet peacefully, but also engage in sportsmanlike conduct. Preaching to the choir, irish rock anthem.

# Beat 8 - Fun & Games
Mascots play baseball with famous players like Garciaparra, Sosa, Bonds, Macguirem, lots of replays and high fives. Red Socks are distributed throughout the stadium and the night market, Neil Diamond's Sweet Caroline plays with added emphasis on touching hands metaphors.

# Fenway Park - Int. Scoreboard - Day

@ Aalfred
" Wally, everyone is counting on you. Come on.

Aalfred holds the door open with his foot, and rolls his arm towards outside.

Wally shakes his head and presses the Kaktovik numerals for the scoreboard.

@ The Announcer
" I can't.

@ Aalfred
" We don't have time for this. Be brave.

Wally continues shaking his head while slowly hitting his keys.

@ The Announcer
" I'm not as young as I used to be.

@ Aalfred
" You don't need to win.

Wally, beginning to cry, sobbing over the controls as he touches them.

@ The Announcer
" I don't want to die.

@ Aalfred
" You'll be okay, now you pull up those socks, you get out there, and you--

Wally stands up and slams the controls.

@ The Announcer
" But they're laughing at me!

@ Aalfred
" Laughing with you!

Wally stands firm and tall, holding the button down.

@ The Announcer
" They're going to kill us. They're going to kill us. They're going to--

@ Aalfred
" -- were. Were going to kill you.

Wally releases the controls.

@ The Announcer
" Were?

Aalfred nods excitedly.

@ Aalfred
" I'm in the past, but this is a new moment. This hasn't happened yet. New time.

Wally leans down onto the controls as he sits again.

@ The Announcer
" I'm confused.

@ Aalfred
" Tonight is the night the multiverse learns about baseball.

Wally raises an eyebrow and taps the controls.

@ Wally
" Nobody cares about baseball anymore.

@ Aalfred
" They will, again. More than ever before.

@ Wally
" Because of us?

Aalfred continues smiling and nodding.

@ Aalfred
" Yes. Now pull up those red socks, get out there, and make them laugh like there's no tomorrow.

Wally stands up, stretches his arms, and jumps twice, and heads out the door.

Aalfred nestles into the controls.

@ The Announcer
" Welcome back to the field, the one, the only, the Eternal Green Monster!

Wally emerges from the doorway on the other side.

^ Fade to white

# Beat 9 - Midpoint
Ronald McDonald (Fey) approaches the real Jane Fonda at a McDonald's parking lot. Jane chooses not to be a traveller in favor of documenting her corner of earth. A ballad about the value of journalism.

# Beat 10 - Bad Guys Close In
Synthia uses the convergence dome and her army of Aalfred's to align with the board of narrative oversight. Aalfred loses credibility, at best he appears a rogue agent. An electronic power pop anthem.

# Beat 11 - All is Lost
Sage is resigned and is going to send Aalfred back if he won't go willingly. Aalfred makes her promise for one last plan. A sorrowful love song.

# Beat 12 - Dark Night of the Soul
Fey becomes an army of Aalfred's to face off with Synthia's army of Aalfred's in the convergence dome. Fey's and Aalfred's transparency become their relateable aspects. Hip-hop, judo, counterpoint.

# Beat 13 - Break Into 3
Jane releases a new documentary, Free the Clowns, which is distributed at the IDUWN Market. Everyone has Red Socks, even the army of Aalfred's. A reprise with Sweet Caroline being the focus.

# Beat 14 - Finale
Aalfred comforts Synthia on the end of existence . An acoustic farewell with a whistled tune, with Synthia collapsing into loose pages on the final note.

# Convergence Dome - Early morning

Aalfred surveys a battlefield of shorn suits across the atrium.

@ Aalfred
" We started with best laid plans

Aalfred clenches his fist and shuts his eyes.

@ Aalfred
" Putting power in many hands
( Smiling
" We made families of friends
( Pensive
" T'was fun, but now we're at the end

Aalfred shakes his head.

@ Synthia
" I thought I was helping
" People were playing while dreaming
" I thought they were sleeping

Aalfred opens his eyes, mortified.

@ Synthia
" Another time they'll be waking

@ Aalfred
" Life is richer and much thicker
" Than computations make believe

Aalfred explodes an imaginary calculator into jazz hands.

@ Aalfred
" Next time you'd calculate quicker
" I know you'll never see

Aalfred winces.

@ Synthia
( optimistic
" The gods played tricks on me
" Said, 'Clowns are an anamoly'
" 'They were never meant to be'
" 'Laughter is just heresy'

Aalfred sighs deeply.

@ Aalfred
" Creativity is messy

Aalfred shakes his tome in memory.

" The gods will always exploit you
" Ones and zeroes never make two
" All our fates must be set free

Aalfred whistles the tune one last time and Synthia collapses into pages.

# Beat 15 - Final Image
Aalfred blowing on a blade of grass in a grove, Sage blushing. Running around trees in the forest and not going anywhere. A more complex, mature rendition of the opening children's song.

Aalfred and Sage journey from the convergence dome to the edge of the serenaded tree.

@ Aalfred
Always whoa.

Aalfred and Sage, surrounded in a musical mist as the serenaded tree bends back into a bridge to the beginning.

@ Sage
This place was always home.

@ Aalfred hums a low D and the rocks and sticks flipping and slapping.

^ Cut to black



original intro

# Ext. Space

The universe brims with possiblity; uncountable stars blink on and off, galaxies spin, but slow down. The camera flows into a Milky Way that continues to grind to a halt and reaches earth as it stops spinning.

# Ext. Earth

The planet is covered in water; only mountaintops peak above the oceans except for one floating redwood forest. In the canopy of the forest, a tree-house meets space-station connects across trunks, providing stability for the floating trees supported with roots bouyed in a thick kelp forest.

# Convergence Dome
# Int. Office

Aalfred's office is fairly narrow, vaulted ceilings, with one column at the end he's standing at and a giant window at the other that has the same swirling aurora borealis monitoring system. In the center of the room are two couches with a coffee table in the center.

To the right of the sitting area is a double wide arched doorway, where Genesis in circular formation rests awaiting Aalfred.

To the left, is a drafting table. The room is sparse, but decorated with curtains and carpets. It feels spacious, but not empty.

Aalfred approaches the center of the room and sits down before glancing over to Genesis.

@ Aalfred
" Okay

Genesis blinks, the window switches from the aurora to an ocean, with waves splashing halfway up and an underwater view halfway down.

@ Genesis
" Okay. I'll send in the first.
